name: updateimages

on:
  push:
#    branches:
#      - main
    tags:
      - v*

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev qemu
      - name: Bring over config files from redpill-load
        run: |
          mkdir /opt/config-files
          cd /opt/config-files
          git clone -b develop https://github.com/pocopico/redpill-load.git
          ls -ltr /opt/config-files/redpill-load/config 
      - name: Build
        run: |
          mkdir /opt/tinycore-redpill
          cd /opt/tinycore-redpill
          ls -ltr . 
          cp -rf /home/runner/work/tinycore-redpill/* .
          VERSION=`/home/runner/work/tinycore-redpill/rploader.sh version`
          echo "Version: ${VERSION}"
          echo '---start Update---'
          ls -ltr /opt/tinycore-redpill
          ls -ltr /opt/config-files
          ls -ltr cp -rf /home/runner/work/tinycore-redpill/

         
      - name: Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
          path: /opt/tinycore-redpill/rploader.sh
