name: updateimages

on:
  push:
#    branches:
#      - main
    tags:
      - v*

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libelf-dev qemu
      - name: Bring over config files from redpill-load
        run: |
          mkdir /opt/config-files
          cd /opt/config-files
          git clone -b develop https://github.com/pocopico/redpill-load.git
          ls -ltr /opt/config-files/redpill-load/config 
      - name: Build
        run: |
          mkdir /opt/tinycore-redpill
          cd /opt/tinycore-redpill
          cp -rfp /home/runner/work/tinycore-redpill/tinycore-redpill/* .
          cp -rfp /opt/config-files/redpill-load/config /opt/tinycore-redpill
          sudo find . -type f -name "*.sh" -exec chmod +x {} \;
          sudo chmod /opt/tinycore-redpill/tools/*
          VERSION=`/opt/tinycore-redpill/rploader.sh version`
          echo "Version: ${VERSION}"
          echo "/opt/tinycore-redpill files" 
          ls -ltr /opt/tinycore-redpill
          echo "/opt/config-files files" 
          ls -ltr /opt/config-files
          echo '---start Update---'
                   
      - name: Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
          path: /opt/tinycore-redpill/rploader.sh
